language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm strictures"
  - "cpanm Moo"
  - "cpanm MooX::Types::MooseLike::Base"
  - "cpanm Test::More"
